pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                sh '''
                rm -rf redbus-docker-conf
                git clone https://github.com/Maksud-Husen/redbus-docker-conf.git
                '''              
            }
        }

        stage('Debug - List Files') {
            steps {
                dir('redbus') {
                    sh 'ls -la'
                }
            }
        }

        stage('Build img') {
            steps {
                echo 'Building Docker images...'

                dir('redbus') {
                    sh 'docker compose -f docker-compose.yml build'
                }
                echo 'Docker images built successfully.'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'docker compose -f redbus/docker-compose.yml build'
            }
        }
    }

    post {
        always {
            echo 'Build completed.'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
