pipeline{
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                sh ' 
                git clone https://github.com/Maksud-Husen/redbus-docker-conf.git
                '   

            }
        }
        stage ('Build img') {
            steps {
                echo 'Building Docker images...'
                sh 'docker-compose -f docker-compose.yml build'
            }
        
        }
        stage ('Deploy') {
            steps {
                echo 'Deploying application...'
                sh 'docker-compose -f docker-compose.yml up -d'
            }
        }

    } 
    post {
        always {
            echo 'Build completed.'
        }
        failure {
            echo 'Build failed.'
        }
    }       
}   