apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: redbus
type: Opaque
data:
  username: bWFraHVz # base64 encoded value of 'makhus'
  password: bWFraHVzNzg2 # base64 encoded value of 'makhus786'